/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List upcoming active bookings across all event types.
         *     Returns bookings where status=active and startTime >= now,
         *     sorted by startTime ascending.
         */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single booking by ID. */
        get: operations["AdminBookings_read"];
        put?: never;
        post?: never;
        /** @description Cancel a booking (owner, no token needed). */
        delete: operations["AdminBookings_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types (includes inactive). */
        get: operations["AdminEvents_list"];
        put?: never;
        /** @description Create a new event type. */
        post: operations["AdminEvents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type by slug. */
        get: operations["AdminEvents_read"];
        put?: never;
        post?: never;
        /** @description Delete an event type. Fails if active bookings exist. */
        delete: operations["AdminEvents_delete"];
        options?: never;
        head?: never;
        /** @description Update an event type. Slug is immutable. */
        patch: operations["AdminEvents_update"];
        trace?: never;
    };
    "/api/v1/public/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Cancel a booking (guest). Requires the cancel token from booking creation. */
        delete: operations["PublicBookings_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List active event types visible to guests. */
        get: operations["PublicEvents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single active event type by slug. */
        get: operations["PublicEvents_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{slug}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a booking for an event. */
        post: operations["PublicEvents_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/events/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get available slots for an event on a specific date. */
        get: operations["PublicEvents_getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current weekly schedule. */
        get: operations["AdminSchedule_get"];
        /** @description Replace the entire weekly schedule. */
        put: operations["AdminSchedule_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A booking created by a guest. */
        Booking: {
            /** @description Server-generated unique identifier. */
            readonly id: string;
            /** @description ID of the booked event type. */
            readonly eventId: string;
            /**
             * Format: date-time
             * @description Booking start time in UTC.
             */
            startTime: string;
            /** @description Booking status. */
            readonly status: components["schemas"]["BookingStatus"];
            /** @description Guest contact information. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Server-generated creation timestamp.
             */
            readonly createdAt: string;
        };
        /** @description Response returned when a booking is created. Includes the one-time cancelToken. */
        BookingCreatedResponse: {
            id: string;
            eventId: string;
            /** Format: date-time */
            startTime: string;
            status: components["schemas"]["BookingStatus"];
            /** @description One-time cancel token. Only returned on creation. */
            cancelToken: string;
            guest: components["schemas"]["Guest"];
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Booking status.
         * @enum {string}
         */
        BookingStatus: "active" | "cancelled";
        /** @description Booking with nested event summary, returned in admin list/detail views. */
        BookingWithEvent: {
            id: string;
            eventId: string;
            /** Format: date-time */
            startTime: string;
            status: components["schemas"]["BookingStatus"];
            guest: components["schemas"]["Guest"];
            /** Format: date-time */
            createdAt: string;
            /** @description Summary of the associated event type. */
            event: components["schemas"]["EventSummary"];
        };
        /** @description Request body for creating a booking. */
        CreateBookingRequest: {
            /**
             * Format: date-time
             * @description Desired slot start time in UTC. Must align with a valid slot.
             */
            startTime: string;
            /** @description Guest contact information. */
            guest: components["schemas"]["Guest"];
        };
        /** @description Request body for creating an event. */
        CreateEventRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            duration: number;
            slug: string;
        };
        /** @description Schedule configuration for a single day of the week. */
        DaySchedule: {
            /** @description Whether this day is available for bookings. */
            enabled: boolean;
            /** @description Time blocks available on this day. Must not overlap. */
            blocks: components["schemas"]["TimeBlock"][];
        };
        /** @description Standard error response. */
        ErrorBody: {
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** @description An event type that guests can book. */
        Event: {
            /** @description Server-generated unique identifier. */
            readonly id: string;
            /** @description Event title (1-100 characters). */
            title: string;
            /** @description Event description (1-1000 characters). */
            description: string;
            /**
             * Format: int32
             * @description Event duration in minutes (5-480).
             */
            duration: number;
            /**
             * @description URL-friendly identifier. Lowercase alphanumeric and hyphens,
             *     must start with a letter. Immutable after creation.
             */
            slug: string;
            /** @description Whether the event is visible to guests. Default: true. */
            active: boolean;
            /**
             * Format: date-time
             * @description Server-generated creation timestamp.
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Server-generated last update timestamp.
             */
            readonly updatedAt: string;
        };
        /** @description Abbreviated event info embedded in booking responses. */
        EventSummary: {
            title: string;
            slug: string;
            /** Format: int32 */
            duration: number;
        };
        /** @description Guest contact information provided when creating a booking. */
        Guest: {
            /** @description Guest full name (1-100 characters). */
            name: string;
            /**
             * Format: email
             * @description Guest email address.
             */
            email: string;
            /** @description Optional notes from the guest (max 500 characters). */
            notes?: string;
        };
        /** @description A computed available time slot. */
        Slot: {
            /**
             * Format: date-time
             * @description Slot start time in UTC.
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Slot end time in UTC (startTime + event duration).
             */
            endTime: string;
        };
        /** @description Response for the available slots query. */
        SlotsResponse: {
            /** @description The queried date (YYYY-MM-DD). */
            date: string;
            /** @description Slug of the event type. */
            eventSlug: string;
            /**
             * Format: int32
             * @description Duration of the event in minutes.
             */
            duration: number;
            /** @description Available time slots. */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * @description A time block within a day (e.g. 09:00-12:00).
         * @example {
         *       "start": "09:00",
         *       "end": "17:00"
         *     }
         */
        TimeBlock: {
            /** @description Block start time in HH:MM format (UTC). */
            start: string;
            /** @description Block end time in HH:MM format (UTC). Must be after start. */
            end: string;
        };
        /** @description Request body for updating an event. Slug is immutable. */
        UpdateEventRequest: {
            title?: string;
            description?: string;
            /** Format: int32 */
            duration?: number;
            active?: boolean;
        };
        Weekdays: {
            monday: components["schemas"]["DaySchedule"];
            tuesday: components["schemas"]["DaySchedule"];
            wednesday: components["schemas"]["DaySchedule"];
            thursday: components["schemas"]["DaySchedule"];
            friday: components["schemas"]["DaySchedule"];
            saturday: components["schemas"]["DaySchedule"];
            sunday: components["schemas"]["DaySchedule"];
        };
        /** @description Owner's weekly availability schedule (singleton). */
        WeeklySchedule: {
            weekdays: components["schemas"]["Weekdays"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingWithEvent"][];
                };
            };
        };
    };
    AdminBookings_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingWithEvent"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminBookings_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminEvents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    AdminEvents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminEvents_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminEvents_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminEvents_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublicBookings_cancel: {
        parameters: {
            query: {
                /** @description The cancel token received when the booking was created. */
                cancelToken: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublicEvents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    PublicEvents_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublicEvents_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCreatedResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublicEvents_getSlots: {
        parameters: {
            query: {
                /** @description Date to query slots for (YYYY-MM-DD). Must be within the 14-day booking window. */
                date: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminSchedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySchedule"];
                };
            };
        };
    };
    AdminSchedule_replace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklySchedule"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklySchedule"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
