import { useState, useCallback, useRef, forwardRef, useImperativeHandle } from 'react';
import {
  TextInput,
  NumberInput,
  Textarea,
  Switch,
  Stack,
  Box,
} from '@mantine/core';
import { useForm } from '@mantine/form';
import { generateSlug, isValidSlug } from '../utils/slug';
import type { EventFormData } from '../api/types';

interface EventFormProps {
  initialData?: Partial<EventFormData>;
  isEdit?: boolean;
  onSubmit: (values: EventFormData) => void;
  isSubmitting?: boolean;
  slugError?: string | null;
}

export interface EventFormRef {
  submit: () => void;
}

export const EventForm = forwardRef<EventFormRef, EventFormProps>(function EventForm({
  initialData,
  isEdit = false,
  onSubmit,
  isSubmitting = false,
  slugError,
}, ref) {
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const slugGeneratedFromTitle = useRef<string>('');

  const form = useForm<EventFormData>({
    initialValues: {
      title: initialData?.title ?? '',
      slug: initialData?.slug ?? '',
      duration: initialData?.duration ?? 30,
      description: initialData?.description ?? '',
      active: initialData?.active ?? true,
    },
    validate: {
      title: (value) => {
        if (!value || value.length < 1) return 'Название обязательно';
        if (value.length > 100) return 'Максимум 100 символов';
        return null;
      },
      slug: (value) => {
        if (!isEdit) {
          if (!value || value.length < 1) return 'Slug обязателен';
          if (!isValidSlug(value)) return 'Только строчные буквы, цифры и дефисы, начиная с буквы';
          if (value.length > 60) return 'Максимум 60 символов';
        }
        return null;
      },
      duration: (value) => {
        if (value < 5) return 'Минимум 5 минут';
        if (value > 480) return 'Максимум 480 минут (8 часов)';
        return null;
      },
      description: (value) => {
        if (!value || value.length < 1) return 'Описание обязательно';
        if (value.length > 1000) return 'Максимум 1000 символов';
        return null;
      },
    },
  });

  // Generate slug from title
  const updateSlugFromTitle = useCallback((title: string) => {
    if (!slugManuallyEdited && !isEdit) {
      const newSlug = generateSlug(title);
      slugGeneratedFromTitle.current = newSlug;
      form.setFieldValue('slug', newSlug);
    }
  }, [slugManuallyEdited, isEdit, form]);

  // Debounced slug generation
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const handleTitleChange = (value: string) => {
    form.setFieldValue('title', value);
    
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    
    debounceRef.current = setTimeout(() => {
      updateSlugFromTitle(value);
    }, 300);
  };

  const handleTitleBlur = () => {
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    updateSlugFromTitle(form.values.title);
  };

  const handleSlugChange = (value: string) => {
    setSlugManuallyEdited(true);
    form.setFieldValue('slug', value);
  };

  // Check if slug was generated from current title
  const isSlugAutoGenerated = !isEdit && form.values.slug === slugGeneratedFromTitle.current;

  // Expose submit method via ref
  useImperativeHandle(ref, () => ({
    submit: () => {
      form.onSubmit(onSubmit)();
    },
  }), [form, onSubmit]);

  return (
    <form onSubmit={form.onSubmit(onSubmit)}>
      <Stack gap="md">
        <TextInput
          label="Название"
          placeholder="Например: Встреча на 30 минут"
          required
          {...form.getInputProps('title')}
          onChange={(e) => handleTitleChange(e.currentTarget.value)}
          onBlur={handleTitleBlur}
          disabled={isSubmitting}
        />

        <TextInput
          label="Slug (URL-идентификатор)"
          placeholder="vstrecha-na-30-minut"
          required={!isEdit}
          disabled={isEdit || isSubmitting}
          description={isEdit 
            ? 'Slug нельзя изменить после создания' 
            : isSlugAutoGenerated 
              ? 'Автоматически сгенерирован из названия. Можно изменить вручную.'
              : 'Только строчные буквы, цифры и дефисы'
          }
          {...form.getInputProps('slug')}
          onChange={(e) => handleSlugChange(e.currentTarget.value)}
          error={slugError || form.errors['slug']}
        />

        <NumberInput
          label="Длительность (минут)"
          placeholder="30"
          required
          min={5}
          max={480}
          step={5}
          {...form.getInputProps('duration')}
          disabled={isSubmitting}
        />

        <Textarea
          label="Описание"
          placeholder="Опишите, что гости могут ожидать от этой встречи..."
          required
          minRows={3}
          maxRows={6}
          {...form.getInputProps('description')}
          disabled={isSubmitting}
        />

        <Box>
          <Switch
            label="Активно (видно гостям)"
            {...form.getInputProps('active', { type: 'checkbox' })}
            disabled={isSubmitting}
          />
        </Box>
      </Stack>
    </form>
  );
});


