services:
  devcontainer:
    user: "1000:1000"
    env_file:
      - ../config/env/dev.env
    build:
      context: ./
      target: devcontainer
    working_dir: /workspace
    volumes:
      - ..:/workspace
    ports:
      - "8080:8080"
      - "3000:3000"
    tty: true
    stdin_open: true
    command: bash

